// Generated by gencpp from file pracs/mysrv.msg
// DO NOT EDIT!


#ifndef PRACS_MESSAGE_MYSRV_H
#define PRACS_MESSAGE_MYSRV_H

#include <ros/service_traits.h>


#include <pracs/mysrvRequest.h>
#include <pracs/mysrvResponse.h>


namespace pracs
{

struct mysrv
{

typedef mysrvRequest Request;
typedef mysrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mysrv
} // namespace pracs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pracs::mysrv > {
  static const char* value()
  {
    return "043c37660891c202c07ae9cb667631f0";
  }

  static const char* value(const ::pracs::mysrv&) { return value(); }
};

template<>
struct DataType< ::pracs::mysrv > {
  static const char* value()
  {
    return "pracs/mysrv";
  }

  static const char* value(const ::pracs::mysrv&) { return value(); }
};


// service_traits::MD5Sum< ::pracs::mysrvRequest> should match
// service_traits::MD5Sum< ::pracs::mysrv >
template<>
struct MD5Sum< ::pracs::mysrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pracs::mysrv >::value();
  }
  static const char* value(const ::pracs::mysrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pracs::mysrvRequest> should match
// service_traits::DataType< ::pracs::mysrv >
template<>
struct DataType< ::pracs::mysrvRequest>
{
  static const char* value()
  {
    return DataType< ::pracs::mysrv >::value();
  }
  static const char* value(const ::pracs::mysrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pracs::mysrvResponse> should match
// service_traits::MD5Sum< ::pracs::mysrv >
template<>
struct MD5Sum< ::pracs::mysrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pracs::mysrv >::value();
  }
  static const char* value(const ::pracs::mysrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pracs::mysrvResponse> should match
// service_traits::DataType< ::pracs::mysrv >
template<>
struct DataType< ::pracs::mysrvResponse>
{
  static const char* value()
  {
    return DataType< ::pracs::mysrv >::value();
  }
  static const char* value(const ::pracs::mysrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRACS_MESSAGE_MYSRV_H
